import { Account, Transaction, Alert } from '../src/types.js';
import { AMLEngine } from './amlEngine.js';

export function generateInitialAMLDataset(): { accounts: Account[]; transactions: Transaction[]; alerts: Alert[] } {
  const accounts: Account[] = [
    // 1. Circular Loop Entities (Operation SpiderWeb)
    {
      id: 'acc-spider-1',
      accountNumber: 'ACC-CY-882910',
      accountHolderName: 'Vanguard Trade Holdings Inc',
      accountType: 'OFFSHORE_LLC',
      jurisdiction: 'Cayman Islands',
      jurisdictionRisk: 'HIGH',
      totalInflow: 18500000,
      totalOutflow: 18200000,
      balance: 1450000,
      currency: 'INR',
      transactionCount: 28,
      riskScore: 89,
      riskTier: 'CRITICAL',
      kycStatus: 'ENHANCED_DUE_DILIGENCE',
      isPEP: false,
      sanctionsListed: false,
      centralityScore: 0.88,
      degreeIn: 6,
      degreeOut: 6,
      createdDate: '2023-04-12T00:00:00Z',
    },
    {
      id: 'acc-spider-2',
      accountNumber: 'ACC-PA-449102',
      accountHolderName: 'Apex Logistics Global SA',
      accountType: 'SHELL_CORP',
      jurisdiction: 'Panama',
      jurisdictionRisk: 'HIGH',
      totalInflow: 9400000,
      totalOutflow: 9200000,
      balance: 520000,
      currency: 'INR',
      transactionCount: 19,
      riskScore: 84,
      riskTier: 'CRITICAL',
      kycStatus: 'ENHANCED_DUE_DILIGENCE',
      isPEP: false,
      sanctionsListed: false,
      centralityScore: 0.76,
      degreeIn: 4,
      degreeOut: 4,
      createdDate: '2023-08-19T00:00:00Z',
    },
    {
      id: 'acc-spider-3',
      accountNumber: 'ACC-CY-991204',
      accountHolderName: 'Helios Mercantile Trading Ltd',
      accountType: 'SHELL_CORP',
      jurisdiction: 'Cyprus',
      jurisdictionRisk: 'HIGH',
      totalInflow: 7800000,
      totalOutflow: 7600000,
      balance: 410000,
      currency: 'INR',
      transactionCount: 16,
      riskScore: 81,
      riskTier: 'CRITICAL',
      kycStatus: 'ENHANCED_DUE_DILIGENCE',
      isPEP: false,
      sanctionsListed: false,
      centralityScore: 0.72,
      degreeIn: 3,
      degreeOut: 3,
      createdDate: '2023-11-05T00:00:00Z',
    },
    {
      id: 'acc-spider-4',
      accountNumber: 'ACC-AE-331092',
      accountHolderName: 'Nautilus Capital FZE',
      accountType: 'IMPORT_EXPORT',
      jurisdiction: 'United Arab Emirates',
      jurisdictionRisk: 'HIGH',
      totalInflow: 12000000,
      totalOutflow: 11800000,
      balance: 890000,
      currency: 'INR',
      transactionCount: 22,
      riskScore: 86,
      riskTier: 'CRITICAL',
      kycStatus: 'ENHANCED_DUE_DILIGENCE',
      isPEP: false,
      sanctionsListed: false,
      centralityScore: 0.81,
      degreeIn: 5,
      degreeOut: 5,
      createdDate: '2024-01-15T00:00:00Z',
    },

    // 2. Structuring / Smurfing Collector & Mules
    {
      id: 'acc-smurf-collector',
      accountNumber: 'ACC-IN-554199',
      accountHolderName: 'BlueSky Realty & Advisory Pvt Ltd',
      accountType: 'SHELL_CORP',
      jurisdiction: 'India',
      jurisdictionRisk: 'LOW',
      totalInflow: 5850000,
      totalOutflow: 5500000,
      balance: 620000,
      currency: 'INR',
      transactionCount: 42,
      riskScore: 92,
      riskTier: 'CRITICAL',
      kycStatus: 'ENHANCED_DUE_DILIGENCE',
      isPEP: false,
      sanctionsListed: false,
      centralityScore: 0.94,
      degreeIn: 12,
      degreeOut: 2,
      createdDate: '2024-03-02T00:00:00Z',
    },
    {
      id: 'acc-mule-1',
      accountNumber: 'ACC-IN-102931',
      accountHolderName: 'Aarav Patel',
      accountType: 'INDIVIDUAL',
      jurisdiction: 'India',
      jurisdictionRisk: 'LOW',
      totalInflow: 4000000,
      totalOutflow: 3880000,
      balance: 120000,
      currency: 'INR',
      transactionCount: 5,
      riskScore: 78,
      riskTier: 'HIGH',
      kycStatus: 'UNVERIFIED',
      isPEP: false,
      sanctionsListed: false,
      centralityScore: 0.35,
      degreeIn: 1,
      degreeOut: 4,
      createdDate: '2024-06-10T00:00:00Z',
    },
    {
      id: 'acc-mule-2',
      accountNumber: 'ACC-IN-102932',
      accountHolderName: 'Priya Sharma',
      accountType: 'INDIVIDUAL',
      jurisdiction: 'India',
      jurisdictionRisk: 'LOW',
      totalInflow: 4500000,
      totalOutflow: 4410000,
      balance: 90000,
      currency: 'INR',
      transactionCount: 6,
      riskScore: 76,
      riskTier: 'HIGH',
      kycStatus: 'UNVERIFIED',
      isPEP: false,
      sanctionsListed: false,
      centralityScore: 0.35,
      degreeIn: 1,
      degreeOut: 5,
      createdDate: '2024-06-11T00:00:00Z',
    },
    {
      id: 'acc-mule-3',
      accountNumber: 'ACC-IN-102933',
      accountHolderName: 'Rahul Verma',
      accountType: 'INDIVIDUAL',
      jurisdiction: 'India',
      jurisdictionRisk: 'LOW',
      totalInflow: 3500000,
      totalOutflow: 3450000,
      balance: 50000,
      currency: 'INR',
      transactionCount: 4,
      riskScore: 74,
      riskTier: 'HIGH',
      kycStatus: 'UNVERIFIED',
      isPEP: false,
      sanctionsListed: false,
      centralityScore: 0.30,
      degreeIn: 1,
      degreeOut: 4,
      createdDate: '2024-06-12T00:00:00Z',
    },
    {
      id: 'acc-mule-4',
      accountNumber: 'ACC-IN-102934',
      accountHolderName: 'Sneha Kapoor',
      accountType: 'INDIVIDUAL',
      jurisdiction: 'India',
      jurisdictionRisk: 'LOW',
      totalInflow: 3000000,
      totalOutflow: 2940000,
      balance: 60000,
      currency: 'INR',
      transactionCount: 4,
      riskScore: 72,
      riskTier: 'HIGH',
      kycStatus: 'UNVERIFIED',
      isPEP: false,
      sanctionsListed: false,
      centralityScore: 0.28,
      degreeIn: 1,
      degreeOut: 3,
      createdDate: '2024-06-15T00:00:00Z',
    },

    // 3. Rapid Dispersion & Fan-Out Hub
    {
      id: 'acc-dispersion-hub',
      accountNumber: 'ACC-BZ-771920',
      accountHolderName: 'Nexus Global Commodities Inc',
      accountType: 'OFFSHORE_LLC',
      jurisdiction: 'Belize',
      jurisdictionRisk: 'HIGH',
      totalInflow: 42000000,
      totalOutflow: 41500000,
      balance: 2100000,
      currency: 'INR',
      transactionCount: 35,
      riskScore: 95,
      riskTier: 'CRITICAL',
      kycStatus: 'ENHANCED_DUE_DILIGENCE',
      isPEP: false,
      sanctionsListed: false,
      centralityScore: 0.96,
      degreeIn: 2,
      degreeOut: 9,
      createdDate: '2023-09-01T00:00:00Z',
    },
    {
      id: 'acc-crypto-1',
      accountNumber: 'ACC-KYC-00912',
      accountHolderName: 'BitSafe OTC Gateway Ltd',
      accountType: 'CRYPTO_EXCHANGE',
      jurisdiction: 'Seychelles',
      jurisdictionRisk: 'HIGH',
      totalInflow: 85000000,
      totalOutflow: 81000000,
      balance: 9200000,
      currency: 'INR',
      transactionCount: 140,
      riskScore: 68,
      riskTier: 'HIGH',
      kycStatus: 'VERIFIED',
      isPEP: false,
      sanctionsListed: false,
      centralityScore: 0.82,
      degreeIn: 15,
      degreeOut: 14,
      createdDate: '2022-05-10T00:00:00Z',
    },
    {
      id: 'acc-crypto-2',
      accountNumber: 'ACC-KYC-00915',
      accountHolderName: 'Horizon Digital Liquidity Desk',
      accountType: 'CRYPTO_EXCHANGE',
      jurisdiction: 'Vanuatu',
      jurisdictionRisk: 'HIGH',
      totalInflow: 64000000,
      totalOutflow: 62000000,
      balance: 6500000,
      currency: 'INR',
      transactionCount: 95,
      riskScore: 66,
      riskTier: 'HIGH',
      kycStatus: 'VERIFIED',
      isPEP: false,
      sanctionsListed: false,
      centralityScore: 0.75,
      degreeIn: 12,
      degreeOut: 11,
      createdDate: '2022-08-14T00:00:00Z',
    },
    {
      id: 'acc-offshore-split1',
      accountNumber: 'ACC-VG-110293',
      accountHolderName: 'Pacific Ocean Ventures BVI',
      accountType: 'SHELL_CORP',
      jurisdiction: 'British Virgin Islands',
      jurisdictionRisk: 'HIGH',
      totalInflow: 14500000,
      totalOutflow: 13000000,
      balance: 1800000,
      currency: 'INR',
      transactionCount: 14,
      riskScore: 82,
      riskTier: 'CRITICAL',
      kycStatus: 'ENHANCED_DUE_DILIGENCE',
      isPEP: false,
      sanctionsListed: false,
      centralityScore: 0.65,
      degreeIn: 3,
      degreeOut: 3,
      createdDate: '2023-07-20T00:00:00Z',
    },

    // 4. PEP & Sanction Designated Accounts
    {
      id: 'acc-pep-1',
      accountNumber: 'ACC-CH-994821',
      accountHolderName: 'Viktor Romanov Holdings',
      accountType: 'PRIVATE_BANKING',
      jurisdiction: 'Cyprus',
      jurisdictionRisk: 'HIGH',
      totalInflow: 38000000,
      totalOutflow: 36000000,
      balance: 7500000,
      currency: 'INR',
      transactionCount: 25,
      riskScore: 97,
      riskTier: 'CRITICAL',
      kycStatus: 'SANCTION_MATCH',
      isPEP: true,
      sanctionsListed: true,
      centralityScore: 0.85,
      degreeIn: 4,
      degreeOut: 5,
      createdDate: '2021-12-01T00:00:00Z',
    },

    // 5. Legitimate Normal Baseline Accounts (Retail, Invoicing, Payroll)
    {
      id: 'acc-norm-corp1',
      accountNumber: 'ACC-IN-330192',
      accountHolderName: 'Bharat Enterprise Tech Solutions',
      accountType: 'RETAIL_BUSINESS',
      jurisdiction: 'India',
      jurisdictionRisk: 'LOW',
      totalInflow: 24000000,
      totalOutflow: 21000000,
      balance: 8500000,
      currency: 'INR',
      transactionCount: 110,
      riskScore: 12,
      riskTier: 'LOW',
      kycStatus: 'VERIFIED',
      isPEP: false,
      sanctionsListed: false,
      centralityScore: 0.45,
      degreeIn: 18,
      degreeOut: 24,
      createdDate: '2020-01-10T00:00:00Z',
    },
    {
      id: 'acc-norm-corp2',
      accountNumber: 'ACC-IN-330195',
      accountHolderName: 'Deccan Supply Chain Logistics',
      accountType: 'RETAIL_BUSINESS',
      jurisdiction: 'India',
      jurisdictionRisk: 'LOW',
      totalInflow: 18000000,
      totalOutflow: 17500000,
      balance: 4200000,
      currency: 'INR',
      transactionCount: 88,
      riskScore: 15,
      riskTier: 'LOW',
      kycStatus: 'VERIFIED',
      isPEP: false,
      sanctionsListed: false,
      centralityScore: 0.40,
      degreeIn: 14,
      degreeOut: 18,
      createdDate: '2021-03-15T00:00:00Z',
    },
    {
      id: 'acc-norm-retail1',
      accountNumber: 'ACC-UK-220194',
      accountHolderName: 'Starlight Retail Superstores UK',
      accountType: 'RETAIL_BUSINESS',
      jurisdiction: 'United Kingdom',
      jurisdictionRisk: 'LOW',
      totalInflow: 31000000,
      totalOutflow: 29000000,
      balance: 6200000,
      currency: 'INR',
      transactionCount: 145,
      riskScore: 10,
      riskTier: 'LOW',
      kycStatus: 'VERIFIED',
      isPEP: false,
      sanctionsListed: false,
      centralityScore: 0.50,
      degreeIn: 30,
      degreeOut: 12,
      createdDate: '2019-11-20T00:00:00Z',
    },
    {
      id: 'acc-norm-indiv1',
      accountNumber: 'ACC-IN-990124',
      accountHolderName: 'Ananya Deshmukh',
      accountType: 'INDIVIDUAL',
      jurisdiction: 'India',
      jurisdictionRisk: 'LOW',
      totalInflow: 1250000,
      totalOutflow: 850000,
      balance: 450000,
      currency: 'INR',
      transactionCount: 45,
      riskScore: 8,
      riskTier: 'LOW',
      kycStatus: 'VERIFIED',
      isPEP: false,
      sanctionsListed: false,
      centralityScore: 0.15,
      degreeIn: 2,
      degreeOut: 12,
      createdDate: '2022-04-18T00:00:00Z',
    },
    {
      id: 'acc-norm-indiv2',
      accountNumber: 'ACC-IN-990127',
      accountHolderName: 'Vikramaditya Rao',
      accountType: 'INDIVIDUAL',
      jurisdiction: 'India',
      jurisdictionRisk: 'LOW',
      totalInflow: 1800000,
      totalOutflow: 1300000,
      balance: 620000,
      currency: 'INR',
      transactionCount: 52,
      riskScore: 6,
      riskTier: 'LOW',
      kycStatus: 'VERIFIED',
      isPEP: false,
      sanctionsListed: false,
      centralityScore: 0.18,
      degreeIn: 3,
      degreeOut: 14,
      createdDate: '2022-01-05T00:00:00Z',
    }
  ];

  const now = Date.now();
  const oneHour = 60 * 60 * 1000;

  // 2. Base transactions list
  const rawTransactions: Array<Omit<Transaction, 'riskScore' | 'flaggedPatterns' | 'status'>> = [
    // --- SCENARIO 1: SpiderWeb Circular Fund Routing ---
    // A -> B -> C -> D -> A
    {
      id: 'tx-spider-1',
      referenceNumber: 'TX-SWIFT-2026-901',
      senderId: 'acc-spider-1',
      senderName: 'Vanguard Trade Holdings Inc',
      senderType: 'OFFSHORE_LLC',
      senderJurisdiction: 'Cayman Islands',
      receiverId: 'acc-spider-2',
      receiverName: 'Apex Logistics Global SA',
      receiverType: 'SHELL_CORP',
      receiverJurisdiction: 'Panama',
      amount: 4800000,
      currency: 'INR',
      timestamp: new Date(now - 72 * oneHour).toISOString(),
      channel: 'SWIFT',
      notes: 'Consultancy and cross-border maritime fees',
    },
    {
      id: 'tx-spider-2',
      referenceNumber: 'TX-WIRE-2026-902',
      senderId: 'acc-spider-2',
      senderName: 'Apex Logistics Global SA',
      senderType: 'SHELL_CORP',
      senderJurisdiction: 'Panama',
      receiverId: 'acc-spider-3',
      receiverName: 'Helios Mercantile Trading Ltd',
      receiverType: 'SHELL_CORP',
      receiverJurisdiction: 'Cyprus',
      amount: 4680000,
      currency: 'INR',
      timestamp: new Date(now - 58 * oneHour).toISOString(),
      channel: 'RTGS',
      notes: 'Commodity forward contract settlement',
    },
    {
      id: 'tx-spider-3',
      referenceNumber: 'TX-SWIFT-2026-903',
      senderId: 'acc-spider-3',
      senderName: 'Helios Mercantile Trading Ltd',
      senderType: 'SHELL_CORP',
      senderJurisdiction: 'Cyprus',
      receiverId: 'acc-spider-4',
      receiverName: 'Nautilus Capital FZE',
      receiverType: 'IMPORT_EXPORT',
      receiverJurisdiction: 'United Arab Emirates',
      amount: 4550000,
      currency: 'INR',
      timestamp: new Date(now - 40 * oneHour).toISOString(),
      channel: 'SWIFT',
      notes: 'Trade finance collateral repatriation',
    },
    {
      id: 'tx-spider-4',
      referenceNumber: 'TX-SWIFT-2026-904',
      senderId: 'acc-spider-4',
      senderName: 'Nautilus Capital FZE',
      senderType: 'IMPORT_EXPORT',
      senderJurisdiction: 'United Arab Emirates',
      receiverId: 'acc-spider-1',
      receiverName: 'Vanguard Trade Holdings Inc',
      receiverType: 'OFFSHORE_LLC',
      receiverJurisdiction: 'Cayman Islands',
      amount: 4420000,
      currency: 'INR',
      timestamp: new Date(now - 22 * oneHour).toISOString(),
      channel: 'SWIFT',
      notes: 'Management service dividend distribution (Completes loop)',
    },

    // --- SCENARIO 2: Smurfing & Structuring Fan-In (< ₹10 Lakhs CTR Threshold Evasion) ---
    {
      id: 'tx-smurf-1',
      referenceNumber: 'TX-NEFT-2026-401',
      senderId: 'acc-mule-1',
      senderName: 'Aarav Patel',
      senderType: 'INDIVIDUAL',
      senderJurisdiction: 'India',
      receiverId: 'acc-smurf-collector',
      receiverName: 'BlueSky Realty & Advisory Pvt Ltd',
      receiverType: 'SHELL_CORP',
      receiverJurisdiction: 'India',
      amount: 980000,
      currency: 'INR',
      timestamp: new Date(now - 36 * oneHour).toISOString(),
      channel: 'NEFT',
      notes: 'Retainer deposit payment tranche 1',
    },
    {
      id: 'tx-smurf-2',
      referenceNumber: 'TX-NEFT-2026-402',
      senderId: 'acc-mule-1',
      senderName: 'Aarav Patel',
      senderType: 'INDIVIDUAL',
      senderJurisdiction: 'India',
      receiverId: 'acc-smurf-collector',
      receiverName: 'BlueSky Realty & Advisory Pvt Ltd',
      receiverType: 'SHELL_CORP',
      receiverJurisdiction: 'India',
      amount: 965000,
      currency: 'INR',
      timestamp: new Date(now - 24 * oneHour).toISOString(),
      channel: 'NEFT',
      notes: 'Retainer deposit payment tranche 2',
    },
    {
      id: 'tx-smurf-3',
      referenceNumber: 'TX-CASH-2026-403',
      senderId: 'acc-mule-2',
      senderName: 'Priya Sharma',
      senderType: 'INDIVIDUAL',
      senderJurisdiction: 'India',
      receiverId: 'acc-smurf-collector',
      receiverName: 'BlueSky Realty & Advisory Pvt Ltd',
      receiverType: 'SHELL_CORP',
      receiverJurisdiction: 'India',
      amount: 990000,
      currency: 'INR',
      timestamp: new Date(now - 20 * oneHour).toISOString(),
      channel: 'CASH_DEPOSIT',
      notes: 'Advisory retainer cash deposit (sub-10L)',
    },
    {
      id: 'tx-smurf-4',
      referenceNumber: 'TX-NEFT-2026-404',
      senderId: 'acc-mule-2',
      senderName: 'Priya Sharma',
      senderType: 'INDIVIDUAL',
      senderJurisdiction: 'India',
      receiverId: 'acc-smurf-collector',
      receiverName: 'BlueSky Realty & Advisory Pvt Ltd',
      receiverType: 'SHELL_CORP',
      receiverJurisdiction: 'India',
      amount: 975000,
      currency: 'INR',
      timestamp: new Date(now - 14 * oneHour).toISOString(),
      channel: 'NEFT',
      notes: 'Commercial appraisal fee tranche',
    },
    {
      id: 'tx-smurf-5',
      referenceNumber: 'TX-NEFT-2026-405',
      senderId: 'acc-mule-3',
      senderName: 'Rahul Verma',
      senderType: 'INDIVIDUAL',
      senderJurisdiction: 'India',
      receiverId: 'acc-smurf-collector',
      receiverName: 'BlueSky Realty & Advisory Pvt Ltd',
      receiverType: 'SHELL_CORP',
      receiverJurisdiction: 'India',
      amount: 995000,
      currency: 'INR',
      timestamp: new Date(now - 10 * oneHour).toISOString(),
      channel: 'NEFT',
      notes: 'Property escrow installment (sub-10L)',
    },
    {
      id: 'tx-smurf-6',
      referenceNumber: 'TX-RTGS-2026-406',
      senderId: 'acc-mule-4',
      senderName: 'Sneha Kapoor',
      senderType: 'INDIVIDUAL',
      senderJurisdiction: 'India',
      receiverId: 'acc-smurf-collector',
      receiverName: 'BlueSky Realty & Advisory Pvt Ltd',
      receiverType: 'SHELL_CORP',
      receiverJurisdiction: 'India',
      amount: 985000,
      currency: 'INR',
      timestamp: new Date(now - 4 * oneHour).toISOString(),
      channel: 'RTGS',
      notes: 'Consulting milestone advance',
    },

    // --- SCENARIO 3: Rapid Layering & Fan-Out Dispersion ---
    {
      id: 'tx-disp-in',
      referenceNumber: 'TX-SWIFT-2026-800',
      senderId: 'acc-spider-4',
      senderName: 'Nautilus Capital FZE',
      senderType: 'IMPORT_EXPORT',
      senderJurisdiction: 'United Arab Emirates',
      receiverId: 'acc-dispersion-hub',
      receiverName: 'Nexus Global Commodities Inc',
      receiverType: 'OFFSHORE_LLC',
      receiverJurisdiction: 'Belize',
      amount: 28500000,
      currency: 'INR',
      timestamp: new Date(now - 3 * oneHour).toISOString(),
      channel: 'SWIFT',
      notes: 'Bulk mineral export liquidation tranche',
    },
    {
      id: 'tx-disp-out-1',
      referenceNumber: 'TX-CRYPTO-2026-801',
      senderId: 'acc-dispersion-hub',
      senderName: 'Nexus Global Commodities Inc',
      senderType: 'OFFSHORE_LLC',
      senderJurisdiction: 'Belize',
      receiverId: 'acc-crypto-1',
      receiverName: 'BitSafe OTC Gateway Ltd',
      receiverType: 'CRYPTO_EXCHANGE',
      receiverJurisdiction: 'Seychelles',
      amount: 9500000,
      currency: 'INR',
      timestamp: new Date(now - 2.5 * oneHour).toISOString(),
      channel: 'CRYPTO_TRANSFER',
      notes: 'Instant OTC settlement liquidity pool',
    },
    {
      id: 'tx-disp-out-2',
      referenceNumber: 'TX-CRYPTO-2026-802',
      senderId: 'acc-dispersion-hub',
      senderName: 'Nexus Global Commodities Inc',
      senderType: 'OFFSHORE_LLC',
      senderJurisdiction: 'Belize',
      receiverId: 'acc-crypto-2',
      receiverName: 'Horizon Digital Liquidity Desk',
      receiverType: 'CRYPTO_EXCHANGE',
      receiverJurisdiction: 'Vanuatu',
      amount: 8800000,
      currency: 'INR',
      timestamp: new Date(now - 2.2 * oneHour).toISOString(),
      channel: 'CRYPTO_TRANSFER',
      notes: 'Digital asset arbitrage tranche',
    },
    {
      id: 'tx-disp-out-3',
      referenceNumber: 'TX-RTGS-2026-803',
      senderId: 'acc-dispersion-hub',
      senderName: 'Nexus Global Commodities Inc',
      senderType: 'OFFSHORE_LLC',
      senderJurisdiction: 'Belize',
      receiverId: 'acc-offshore-split1',
      receiverName: 'Pacific Ocean Ventures BVI',
      receiverType: 'SHELL_CORP',
      receiverJurisdiction: 'British Virgin Islands',
      amount: 8200000,
      currency: 'INR',
      timestamp: new Date(now - 2.0 * oneHour).toISOString(),
      channel: 'RTGS',
      notes: 'Intercompany cross-border liquidity loan',
    },

    // --- SCENARIO 4: PEP / Sanction Linked Activity ---
    {
      id: 'tx-pep-1',
      referenceNumber: 'TX-SWIFT-2026-110',
      senderId: 'acc-pep-1',
      senderName: 'Viktor Romanov Holdings',
      senderType: 'PRIVATE_BANKING',
      senderJurisdiction: 'Cyprus',
      receiverId: 'acc-spider-1',
      receiverName: 'Vanguard Trade Holdings Inc',
      receiverType: 'OFFSHORE_LLC',
      receiverJurisdiction: 'Cayman Islands',
      amount: 6500000,
      currency: 'INR',
      timestamp: new Date(now - 48 * oneHour).toISOString(),
      channel: 'SWIFT',
      notes: 'Trust dividend repatriation',
    },

    // --- SCENARIO 5: Legitimate Normal Baseline Transactions ---
    {
      id: 'tx-norm-1',
      referenceNumber: 'TX-NEFT-2026-001',
      senderId: 'acc-norm-corp1',
      senderName: 'Bharat Enterprise Tech Solutions',
      senderType: 'RETAIL_BUSINESS',
      senderJurisdiction: 'India',
      receiverId: 'acc-norm-indiv1',
      receiverName: 'Ananya Deshmukh',
      receiverType: 'INDIVIDUAL',
      receiverJurisdiction: 'India',
      amount: 64000,
      currency: 'INR',
      timestamp: new Date(now - 12 * oneHour).toISOString(),
      channel: 'NEFT',
      notes: 'Monthly executive payroll credit',
    },
    {
      id: 'tx-norm-2',
      referenceNumber: 'TX-NEFT-2026-002',
      senderId: 'acc-norm-corp1',
      senderName: 'Bharat Enterprise Tech Solutions',
      senderType: 'RETAIL_BUSINESS',
      senderJurisdiction: 'India',
      receiverId: 'acc-norm-indiv2',
      receiverName: 'Vikramaditya Rao',
      receiverType: 'INDIVIDUAL',
      receiverJurisdiction: 'India',
      amount: 72000,
      currency: 'INR',
      timestamp: new Date(now - 12 * oneHour).toISOString(),
      channel: 'NEFT',
      notes: 'Monthly senior lead engineer payroll',
    },
    {
      id: 'tx-norm-3',
      referenceNumber: 'TX-RTGS-2026-003',
      senderId: 'acc-norm-corp1',
      senderName: 'Bharat Enterprise Tech Solutions',
      senderType: 'RETAIL_BUSINESS',
      senderJurisdiction: 'India',
      receiverId: 'acc-norm-corp2',
      receiverName: 'Deccan Supply Chain Logistics',
      receiverType: 'RETAIL_BUSINESS',
      receiverJurisdiction: 'India',
      amount: 345000,
      currency: 'INR',
      timestamp: new Date(now - 8 * oneHour).toISOString(),
      channel: 'RTGS',
      notes: 'Quarterly hardware freight vendor invoice #8892',
    },
    {
      id: 'tx-norm-4',
      referenceNumber: 'TX-SWIFT-2026-004',
      senderId: 'acc-norm-corp2',
      senderName: 'Deccan Supply Chain Logistics',
      senderType: 'RETAIL_BUSINESS',
      senderJurisdiction: 'India',
      receiverId: 'acc-norm-retail1',
      receiverName: 'Starlight Retail Superstores UK',
      receiverType: 'RETAIL_BUSINESS',
      receiverJurisdiction: 'United Kingdom',
      amount: 1120000,
      currency: 'INR',
      timestamp: new Date(now - 18 * oneHour).toISOString(),
      channel: 'SWIFT',
      notes: 'Container inventory settlement FOB Mumbai-Southampton',
    },
    {
      id: 'tx-norm-5',
      referenceNumber: 'TX-CARD-2026-005',
      senderId: 'acc-norm-indiv1',
      senderName: 'Ananya Deshmukh',
      senderType: 'INDIVIDUAL',
      senderJurisdiction: 'India',
      receiverId: 'acc-norm-retail1',
      receiverName: 'Starlight Retail Superstores UK',
      receiverType: 'RETAIL_BUSINESS',
      receiverJurisdiction: 'United Kingdom',
      amount: 2400,
      currency: 'INR',
      timestamp: new Date(now - 6 * oneHour).toISOString(),
      channel: 'CARD',
      notes: 'Online store purchase debit',
    },
    {
      id: 'tx-norm-6',
      referenceNumber: 'TX-NEFT-2026-006',
      senderId: 'acc-norm-indiv2',
      senderName: 'Vikramaditya Rao',
      senderType: 'INDIVIDUAL',
      senderJurisdiction: 'India',
      receiverId: 'acc-norm-corp1',
      receiverName: 'Bharat Enterprise Tech Solutions',
      receiverType: 'RETAIL_BUSINESS',
      receiverJurisdiction: 'India',
      amount: 15000,
      currency: 'INR',
      timestamp: new Date(now - 30 * oneHour).toISOString(),
      channel: 'NEFT',
      notes: 'Hardware laptop security deposit reimbursement',
    }
  ];

  // Initialize AML Engine to compute initial risk scores and alerts
  const engine = new AMLEngine(accounts, [], []);

  rawTransactions.forEach(rawTx => {
    engine.ingestTransaction(rawTx);
  });

  return {
    accounts: engine.getAccounts(),
    transactions: engine.getTransactions(),
    alerts: engine.getAlerts(),
  };
}
